export const ALL_SETTING_KEYS: string[] = [
  "HUB_URL", "BUILDER_URL", "DEPLOY_URL",
  "GITHUB_TOKEN", "GITHUB_ORG", "HUB_REPO", "BUILDER_REPO", "DEPLOY_REPO",
  "HUB_SERVER_HOST", "BUILDER_SERVER_HOST", "DEPLOY_SERVER_HOST",
  "SSH_USERNAME", "WATCHDOG_SSH_KEY",
  "SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASS", "ALERT_EMAIL",
  "ANTHROPIC_API_KEY", "OPENAI_API_KEY",
  "AUTO_REPAIR", "WATCHDOG_URL",
];
